In [1]:
import pandas as pd

df = pd.read_csv("https://github.com/Patil-Sravani/food_delivery_time_prediction/raw/refs/heads/main/Food_Delivery_Time_Prediction.csv")

In [2]:
df.head()

,Order_ID,Order_Date,Order_Hour,Day_of_Week,Is_Weekend,Is_Festival,Weather,Pickup_Zone,Dropoff_Zone,Vehicle_Type,...,Order_Items,Restaurant_Load,Preparation_Time_Min,Road_Distance_km,Delivery_Distance_Category,Traffic_Level,Number_of_Signals,Average_Speed_kmph,Delivery_Priority,Time_taken_min
0,ORD000001,2025-10-28,8,Tuesday,0,0,Clear,CBD,Commercial,Scooter,...,1,Medium,23,30.55,Long,Moderate,15,28.7,Normal,91
1,ORD000002,2025-09-26,12,Friday,0,0,Rain,CBD,CBD,Scooter,...,3,Medium,11,2.25,Short,Moderate,17,23.3,Normal,21
2,ORD000003,2025-01-26,18,Sunday,1,0,Clear,Residential,Residential,Scooter,...,1,Low,31,10.15,Long,Moderate,8,28.9,Normal,52
3,ORD000004,2025-11-19,12,Wednesday,0,0,Cloudy,Residential,Industrial,Bike,...,3,Medium,19,26.33,Long,Low,9,41.4,Normal,59
4,ORD000005,2025-08-04,18,Monday,0,0,Rain,Industrial,Residential,Bike,...,1,Medium,7,30.48,Long,Moderate,8,31.7,Normal,75

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 24 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Order_ID                    50000 non-null  str
 1   Order_Date                  50000 non-null  str
 2   Order_Hour                  50000 non-null  int64
 3   Day_of_Week                 50000 non-null  str
 4   Is_Weekend                  50000 non-null  int64
 5   Is_Festival                 50000 non-null  int64
 6   Weather                     50000 non-null  str
 7   Pickup_Zone                 50000 non-null  str
 8   Dropoff_Zone                50000 non-null  str
 9   Vehicle_Type                50000 non-null  str
 10  Rider_Experience_Years      50000 non-null  float64
 11  Rider_Rating                50000 non-null  float64
 12  Restaurant_Rating           50000 non-null  float64
 13  Cuisine_Type                50000 non-null  str
 14  Order_Items                 50000 non-null  int64
 15  Restaurant_Load             50000 non-null  str
 16  Preparation_Time_Min        50000 non-null  int64
 17  Road_Distance_km            50000 non-null  float64
 18  Delivery_Distance_Category  50000 non-null  str
 19  Traffic_Level               50000 non-null  str
 20  Number_of_Signals           50000 non-null  int64
 21  Average_Speed_kmph          50000 non-null  float64
 22  Delivery_Priority           50000 non-null  str
 23  Time_taken_min              50000 non-null  int64
dtypes: float64(5), int64(7), str(12)
memory usage: 13.1 MB

In [4]:
df.describe()

,Order_Hour,Is_Weekend,Is_Festival,Rider_Experience_Years,Rider_Rating,Restaurant_Rating,Order_Items,Preparation_Time_Min,Road_Distance_km,Number_of_Signals,Average_Speed_kmph,Time_taken_min
count,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.00000,50000.000000,50000.000000,50000.000000,50000.000000
mean,13.847700,0.283600,0.049100,4.439744,3.951646,4.175368,2.652740,24.03118,26.201744,9.728920,31.759634,83.868980
std,5.525291,0.450749,0.216079,2.927752,0.294960,0.356201,1.590359,8.34877,12.620079,4.330849,9.510842,35.426899
min,0.000000,0.000000,0.000000,0.100000,3.200000,3.300000,1.000000,5.00000,0.080000,2.000000,8.000000,10.000000
25%,10.000000,0.000000,0.000000,2.200000,3.700000,3.900000,1.000000,18.00000,16.330000,6.000000,25.300000,58.000000
50%,14.000000,0.000000,0.000000,3.800000,3.900000,4.200000,2.000000,24.00000,25.620000,9.000000,33.100000,78.000000
75%,19.000000,1.000000,0.000000,5.900000,4.100000,4.400000,4.000000,30.00000,35.480000,14.000000,39.600000,102.000000
max,23.000000,1.000000,1.000000,15.000000,5.000000,5.000000,7.000000,51.00000,70.820000,18.000000,48.300000,180.000000

In [5]:
df.describe(include='all')

,Order_ID,Order_Date,Order_Hour,Day_of_Week,Is_Weekend,Is_Festival,Weather,Pickup_Zone,Dropoff_Zone,Vehicle_Type,...,Order_Items,Restaurant_Load,Preparation_Time_Min,Road_Distance_km,Delivery_Distance_Category,Traffic_Level,Number_of_Signals,Average_Speed_kmph,Delivery_Priority,Time_taken_min
count,50000,50000,50000.000000,50000,50000.000000,50000.000000,50000,50000,50000,50000,...,50000.000000,50000,50000.00000,50000.000000,50000,50000,50000.000000,50000.000000,50000,50000.000000
unique,50000,365,NaN,7,NaN,NaN,5,5,5,4,...,NaN,3,NaN,NaN,3,4,NaN,NaN,3,NaN
top,ORD000001,2025-02-12,NaN,Tuesday,NaN,NaN,Clear,Residential,Residential,Bike,...,NaN,Low,NaN,NaN,Long,Low,NaN,NaN,Normal,NaN
freq,1,170,NaN,7264,NaN,NaN,23992,15786,16106,22943,...,NaN,17751,NaN,NaN,47238,32567,NaN,NaN,37065,NaN
mean,NaN,NaN,13.847700,NaN,0.283600,0.049100,NaN,NaN,NaN,NaN,...,2.652740,NaN,24.03118,26.201744,NaN,NaN,9.728920,31.759634,NaN,83.868980
std,NaN,NaN,5.525291,NaN,0.450749,0.216079,NaN,NaN,NaN,NaN,...,1.590359,NaN,8.34877,12.620079,NaN,NaN,4.330849,9.510842,NaN,35.426899
min,NaN,NaN,0.000000,NaN,0.000000,0.000000,NaN,NaN,NaN,NaN,...,1.000000,NaN,5.00000,0.080000,NaN,NaN,2.000000,8.000000,NaN,10.000000
25%,NaN,NaN,10.000000,NaN,0.000000,0.000000,NaN,NaN,NaN,NaN,...,1.000000,NaN,18.00000,16.330000,NaN,NaN,6.000000,25.300000,NaN,58.000000
50%,NaN,NaN,14.000000,NaN,0.000000,0.000000,NaN,NaN,NaN,NaN,...,2.000000,NaN,24.00000,25.620000,NaN,NaN,9.000000,33.100000,NaN,78.000000
75%,NaN,NaN,19.000000,NaN,1.000000,0.000000,NaN,NaN,NaN,NaN,...,4.000000,NaN,30.00000,35.480000,NaN,NaN,14.000000,39.600000,NaN,102.000000
max,NaN,NaN,23.000000,NaN,1.000000,1.000000,NaN,NaN,NaN,NaN,...,7.000000,NaN,51.00000,70.820000,NaN,NaN,18.000000,48.300000,NaN,180.000000

In [6]:
df.isnull().sum()

Order_ID                      0
Order_Date                    0
Order_Hour                    0
Day_of_Week                   0
Is_Weekend                    0
Is_Festival                   0
Weather                       0
Pickup_Zone                   0
Dropoff_Zone                  0
Vehicle_Type                  0
Rider_Experience_Years        0
Rider_Rating                  0
Restaurant_Rating             0
Cuisine_Type                  0
Order_Items                   0
Restaurant_Load               0
Preparation_Time_Min          0
Road_Distance_km              0
Delivery_Distance_Category    0
Traffic_Level                 0
Number_of_Signals             0
Average_Speed_kmph            0
Delivery_Priority             0
Time_taken_min                0
dtype: int64

In [7]:
df.columns

Index(['Order_ID', 'Order_Date', 'Order_Hour', 'Day_of_Week', 'Is_Weekend',
       'Is_Festival', 'Weather', 'Pickup_Zone', 'Dropoff_Zone', 'Vehicle_Type',
       'Rider_Experience_Years', 'Rider_Rating', 'Restaurant_Rating',
       'Cuisine_Type', 'Order_Items', 'Restaurant_Load',
       'Preparation_Time_Min', 'Road_Distance_km',
       'Delivery_Distance_Category', 'Traffic_Level', 'Number_of_Signals',
       'Average_Speed_kmph', 'Delivery_Priority', 'Time_taken_min'],
      dtype='str')

In [8]:
df.columns = df.columns.str.lower()
df.columns

Index(['order_id', 'order_date', 'order_hour', 'day_of_week', 'is_weekend',
       'is_festival', 'weather', 'pickup_zone', 'dropoff_zone', 'vehicle_type',
       'rider_experience_years', 'rider_rating', 'restaurant_rating',
       'cuisine_type', 'order_items', 'restaurant_load',
       'preparation_time_min', 'road_distance_km',
       'delivery_distance_category', 'traffic_level', 'number_of_signals',
       'average_speed_kmph', 'delivery_priority', 'time_taken_min'],
      dtype='str')

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
df.rename(columns={'time_taken_min':'delivery_time'},inplace=True)
df.columns

Index(['order_id', 'order_date', 'order_hour', 'day_of_week', 'is_weekend',
       'is_festival', 'weather', 'pickup_zone', 'dropoff_zone', 'vehicle_type',
       'rider_experience_years', 'rider_rating', 'restaurant_rating',
       'cuisine_type', 'order_items', 'restaurant_load',
       'preparation_time_min', 'road_distance_km',
       'delivery_distance_category', 'traffic_level', 'number_of_signals',
       'average_speed_kmph', 'delivery_priority', 'delivery_time'],
      dtype='str')

In [11]:
# create a column vehicle type
vehicle = df['vehicle_type'].value_counts()
vehicle

vehicle_type
Bike                22943
Scooter             12895
Electric Scooter     8852
Bicycle              5310
Name: count, dtype: int64

In [12]:
df[['day_of_week','order_items']].head(10)

  day_of_week  order_items
0     Tuesday            1
1      Friday            3
2      Sunday            1
3   Wednesday            3
4      Monday            1
5   Wednesday            1
6     Tuesday            5
7      Friday            3
8    Thursday            3
9      Friday            6

In [13]:
df[['vehicle_type','rider_rating']].head(10)

       vehicle_type  rider_rating
0           Scooter           3.8
1           Scooter           3.6
2           Scooter           3.9
3              Bike           3.9
4              Bike           4.4
5  Electric Scooter           3.5
6           Bicycle           4.0
7  Electric Scooter           3.7
8              Bike           4.4
9              Bike           4.3

In [14]:
df[['cuisine_type','preparation_time_min']].head(10)

   cuisine_type  preparation_time_min
0         Pizza                    23
1      Desserts                    11
2       Biryani                    31
3        Burger                    19
4      Desserts                     7
5  South Indian                    16
6        Bakery                    13
7        Burger                    23
8  North Indian                    33
9      Desserts                    18

In [15]:
df[['pickup_zone','dropoff_zone']].head(10)

   pickup_zone dropoff_zone
0          CBD   Commercial
1          CBD          CBD
2  Residential  Residential
3  Residential   Industrial
4   Industrial  Residential
5          CBD     Suburban
6   Commercial   Commercial
7          CBD  Residential
8          CBD  Residential
9   Commercial  Residential

In [16]:
df[['order_hour','vehicle_type','traffic_level','delivery_time']].head(10)

   order_hour      vehicle_type traffic_level  delivery_time
0           8           Scooter      Moderate             91
1          12           Scooter      Moderate             21
2          18           Scooter      Moderate             52
3          12              Bike           Low             59
4          18              Bike      Moderate             75
5          18  Electric Scooter      Moderate            105
6          12           Bicycle           Low            180
7          22  Electric Scooter           Low             37
8           8              Bike          High            110
9          16              Bike           Low             69

In [17]:
df[(df['vehicle_type']=='Bike') & (df['delivery_time']<20)].head()

,order_id,order_date,order_hour,day_of_week,is_weekend,is_festival,weather,pickup_zone,dropoff_zone,vehicle_type,...,order_items,restaurant_load,preparation_time_min,road_distance_km,delivery_distance_category,traffic_level,number_of_signals,average_speed_kmph,delivery_priority,delivery_time
1265,ORD001266,2025-09-30,20,Tuesday,0,0,Clear,Residential,Suburban,Bike,...,1,High,10,5.86,Medium,Low,9,42.5,VIP,19
2510,ORD002511,2025-01-23,19,Thursday,0,0,Clear,Commercial,CBD,Bike,...,1,Medium,9,3.08,Medium,Low,13,42.9,Normal,19
3619,ORD003620,2025-09-13,16,Saturday,1,0,Clear,Residential,Commercial,Bike,...,1,Low,6,6.46,Medium,Low,8,42.5,Priority,18
3701,ORD003702,2025-12-04,0,Thursday,0,0,Cloudy,Residential,Industrial,Bike,...,1,Medium,5,4.22,Medium,Low,8,42.1,Normal,18
4846,ORD004847,2025-12-05,20,Friday,0,0,Clear,Suburban,Suburban,Bike,...,1,Low,14,3.97,Medium,Low,3,42.5,Normal,19

In [18]:
df[(df['weather']=='Rain') & (df['traffic_level']=='High')].head(10)

,order_id,order_date,order_hour,day_of_week,is_weekend,is_festival,weather,pickup_zone,dropoff_zone,vehicle_type,...,order_items,restaurant_load,preparation_time_min,road_distance_km,delivery_distance_category,traffic_level,number_of_signals,average_speed_kmph,delivery_priority,delivery_time
21,ORD000022,2025-01-25,15,Saturday,1,1,Rain,Commercial,Commercial,Bike,...,6,Medium,38,17.60,Long,High,12,23.3,Normal,99
25,ORD000026,2025-03-02,20,Sunday,1,0,Rain,Commercial,Residential,Electric Scooter,...,1,Low,13,9.17,Long,High,11,16.4,Normal,55
42,ORD000043,2025-01-12,19,Sunday,1,0,Rain,Suburban,CBD,Scooter,...,4,Low,21,52.45,Long,High,6,18.6,Priority,180
79,ORD000080,2025-02-22,12,Saturday,1,0,Rain,CBD,CBD,Electric Scooter,...,3,Low,28,43.02,Long,High,17,16.4,Priority,180
104,ORD000105,2025-03-06,18,Thursday,0,1,Rain,Commercial,Residential,Bike,...,4,Medium,21,43.43,Long,High,11,23.9,Normal,141
111,ORD000112,2025-12-19,18,Friday,0,0,Rain,CBD,Residential,Bike,...,1,Low,19,26.95,Long,High,14,22.7,Normal,103
188,ORD000189,2025-06-21,20,Saturday,1,0,Rain,Residential,Commercial,Scooter,...,1,Low,17,13.40,Long,High,10,19.0,Normal,70
189,ORD000190,2025-06-01,14,Sunday,1,0,Rain,CBD,Commercial,Electric Scooter,...,1,High,18,8.24,Long,High,18,16.6,Normal,58
199,ORD000200,2025-10-31,21,Friday,0,1,Rain,Residential,CBD,Bike,...,5,Low,16,19.77,Long,High,10,23.7,Normal,79
217,ORD000218,2025-08-31,18,Sunday,1,0,Rain,Residential,CBD,Bike,...,2,High,37,22.31,Long,High,6,23.0,Normal,101

In [19]:
pip install psycopg2-binary sqlalchemy

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: psycopg2-binary in .\AppData\Roaming\Python\Python314\site-packages (2.9.12)
Requirement already satisfied: sqlalchemy in C:\ProgramData\anaconda3\Lib\site-packages (2.0.51)
Requirement already satisfied: greenlet>=1 in C:\ProgramData\anaconda3\Lib\site-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\ProgramData\anaconda3\Lib\site-packages (from sqlalchemy) (4.16.0)
Note: you may need to restart the kernel to use updated packages.

In [20]:
from sqlalchemy import create_engine

# Step 1: Connect to PostgreSQL
# Replace placeholders with your actual details
username = "postgres"      # default user
password = "venkat" # the password you set during installation
host = "localhost"         # if running locally
port = "5432"              # default PostgreSQL port
database = "food_delivery"    # the database you created in pgAdmin

engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

# Step 2: Load DataFrame into PostgreSQL
table_name = "food_delivery"   # choose any table name
df.to_sql(table_name, engine, if_exists="replace", index=False)

print(f"Data successfully loaded into table '{table_name}' in database '{database}'.")

Data successfully loaded into table 'food_delivery' in database 'food_delivery'.